// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace nsRunMode
{

public enum eLngRunMode : short
{
 IN_RUN_MODE = 0,
 IN_MAINTENANCE_MODE = 1,
 MSGID = 2,
 PADDING01 = 3,
 MAX_LNG_RUNMODE_ITEM = 4,
};


}
