// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MitMAP
{

public enum format : sbyte
{
 Ascii = 1,
 Hex = 2,
 Dec = 3,
};


}
