// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MitMAP
{

using global::System;
using global::FlatBuffers;

public struct stXY : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public stXY __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short X { get { return __p.bb.GetShort(__p.bb_pos + 0); } }
  public short Y { get { return __p.bb.GetShort(__p.bb_pos + 2); } }

  public static Offset<stXY> CreatestXY(FlatBufferBuilder builder, short X, short Y) {
    builder.Prep(2, 4);
    builder.PutShort(Y);
    builder.PutShort(X);
    return new Offset<stXY>(builder.Offset);
  }
};


}
