// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MITMAP_MITMAP_H_
#define FLATBUFFERS_GENERATED_MITMAP_MITMAP_H_

#include "flatbuffers/flatbuffers.h"

namespace MitMAP {

struct stXY;

struct MAP;

enum format {
  format_Ascii = 1,
  format_Hex = 2,
  format_Dec = 3,
  format_MIN = format_Ascii,
  format_MAX = format_Dec
};

inline const format (&EnumValuesformat())[3] {
  static const format values[] = {
    format_Ascii,
    format_Hex,
    format_Dec
  };
  return values;
}

inline const char * const *EnumNamesformat() {
  static const char * const names[] = {
    "Ascii",
    "Hex",
    "Dec",
    nullptr
  };
  return names;
}

inline const char *EnumNameformat(format e) {
  const size_t index = static_cast<int>(e) - static_cast<int>(format_Ascii);
  return EnumNamesformat()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) stXY FLATBUFFERS_FINAL_CLASS {
 private:
  int16_t x_;
  int16_t y_;

 public:
  stXY() {
    memset(this, 0, sizeof(stXY));
  }
  stXY(int16_t _x, int16_t _y)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)) {
  }
  int16_t x() const {
    return flatbuffers::EndianScalar(x_);
  }
  int16_t y() const {
    return flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(stXY, 4);

struct MAP FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_MAXROW = 4,
    VT_MAXCOL = 6,
    VT_MAP = 8,
    VT_TARGETDIE = 10,
    VT_REFDIE = 12,
    VT_REFCHIPDIR = 14,
    VT_REFNOTCH = 16,
    VT_DEGROTATED = 18,
    VT_DIESIZEX = 20,
    VT_DIESIZEY = 22,
    VT_DIEGAPX = 24,
    VT_DIEGAPY = 26,
    VT_EDGECLEARANCE = 28,
    VT_DIAMETER = 30,
    VT_WAFERNUM = 32,
    VT_WAFERFAB = 34,
    VT_FABCODE = 36,
    VT_INTCODE = 38,
    VT_LOTNUM = 40,
    VT_DEVICE = 42,
    VT_DESIGNID = 44,
    VT_LAYOUT = 46,
    VT_SCRIBID = 48,
    VT_SCRIBLOT = 50,
    VT_MAPID = 52,
    VT_STARTLOC = 54,
    VT_NULLBIN = 56,
    VT_BINCODEFORMAT = 58
  };
  int16_t maxRow() const {
    return GetField<int16_t>(VT_MAXROW, 0);
  }
  int16_t maxCol() const {
    return GetField<int16_t>(VT_MAXCOL, 0);
  }
  const flatbuffers::Vector<int16_t> *map() const {
    return GetPointer<const flatbuffers::Vector<int16_t> *>(VT_MAP);
  }
  const flatbuffers::Vector<const stXY *> *targetDie() const {
    return GetPointer<const flatbuffers::Vector<const stXY *> *>(VT_TARGETDIE);
  }
  const flatbuffers::Vector<const stXY *> *refDie() const {
    return GetPointer<const flatbuffers::Vector<const stXY *> *>(VT_REFDIE);
  }
  int16_t refChipDir() const {
    return GetField<int16_t>(VT_REFCHIPDIR, 0);
  }
  int16_t refNotch() const {
    return GetField<int16_t>(VT_REFNOTCH, 0);
  }
  int16_t degRotated() const {
    return GetField<int16_t>(VT_DEGROTATED, 0);
  }
  float dieSizeX() const {
    return GetField<float>(VT_DIESIZEX, 0.0f);
  }
  float dieSizeY() const {
    return GetField<float>(VT_DIESIZEY, 0.0f);
  }
  float dieGapX() const {
    return GetField<float>(VT_DIEGAPX, 0.0f);
  }
  float dieGapY() const {
    return GetField<float>(VT_DIEGAPY, 0.0f);
  }
  float edgeClearance() const {
    return GetField<float>(VT_EDGECLEARANCE, 5.0f);
  }
  float diameter() const {
    return GetField<float>(VT_DIAMETER, 200.0f);
  }
  const flatbuffers::String *waferNum() const {
    return GetPointer<const flatbuffers::String *>(VT_WAFERNUM);
  }
  const flatbuffers::String *waferFab() const {
    return GetPointer<const flatbuffers::String *>(VT_WAFERFAB);
  }
  const flatbuffers::String *fabCode() const {
    return GetPointer<const flatbuffers::String *>(VT_FABCODE);
  }
  const flatbuffers::String *intCode() const {
    return GetPointer<const flatbuffers::String *>(VT_INTCODE);
  }
  const flatbuffers::String *lotNum() const {
    return GetPointer<const flatbuffers::String *>(VT_LOTNUM);
  }
  const flatbuffers::String *device() const {
    return GetPointer<const flatbuffers::String *>(VT_DEVICE);
  }
  const flatbuffers::String *designId() const {
    return GetPointer<const flatbuffers::String *>(VT_DESIGNID);
  }
  const flatbuffers::String *layout() const {
    return GetPointer<const flatbuffers::String *>(VT_LAYOUT);
  }
  const flatbuffers::String *scribId() const {
    return GetPointer<const flatbuffers::String *>(VT_SCRIBID);
  }
  const flatbuffers::String *scribLot() const {
    return GetPointer<const flatbuffers::String *>(VT_SCRIBLOT);
  }
  int16_t mapId() const {
    return GetField<int16_t>(VT_MAPID, 0);
  }
  const stXY *startLoc() const {
    return GetStruct<const stXY *>(VT_STARTLOC);
  }
  int16_t nullBin() const {
    return GetField<int16_t>(VT_NULLBIN, 0);
  }
  format bincodeFormat() const {
    return static_cast<format>(GetField<int8_t>(VT_BINCODEFORMAT, 1));
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_MAXROW) &&
           VerifyField<int16_t>(verifier, VT_MAXCOL) &&
           VerifyOffset(verifier, VT_MAP) &&
           verifier.VerifyVector(map()) &&
           VerifyOffset(verifier, VT_TARGETDIE) &&
           verifier.VerifyVector(targetDie()) &&
           VerifyOffset(verifier, VT_REFDIE) &&
           verifier.VerifyVector(refDie()) &&
           VerifyField<int16_t>(verifier, VT_REFCHIPDIR) &&
           VerifyField<int16_t>(verifier, VT_REFNOTCH) &&
           VerifyField<int16_t>(verifier, VT_DEGROTATED) &&
           VerifyField<float>(verifier, VT_DIESIZEX) &&
           VerifyField<float>(verifier, VT_DIESIZEY) &&
           VerifyField<float>(verifier, VT_DIEGAPX) &&
           VerifyField<float>(verifier, VT_DIEGAPY) &&
           VerifyField<float>(verifier, VT_EDGECLEARANCE) &&
           VerifyField<float>(verifier, VT_DIAMETER) &&
           VerifyOffset(verifier, VT_WAFERNUM) &&
           verifier.VerifyString(waferNum()) &&
           VerifyOffset(verifier, VT_WAFERFAB) &&
           verifier.VerifyString(waferFab()) &&
           VerifyOffset(verifier, VT_FABCODE) &&
           verifier.VerifyString(fabCode()) &&
           VerifyOffset(verifier, VT_INTCODE) &&
           verifier.VerifyString(intCode()) &&
           VerifyOffset(verifier, VT_LOTNUM) &&
           verifier.VerifyString(lotNum()) &&
           VerifyOffset(verifier, VT_DEVICE) &&
           verifier.VerifyString(device()) &&
           VerifyOffset(verifier, VT_DESIGNID) &&
           verifier.VerifyString(designId()) &&
           VerifyOffset(verifier, VT_LAYOUT) &&
           verifier.VerifyString(layout()) &&
           VerifyOffset(verifier, VT_SCRIBID) &&
           verifier.VerifyString(scribId()) &&
           VerifyOffset(verifier, VT_SCRIBLOT) &&
           verifier.VerifyString(scribLot()) &&
           VerifyField<int16_t>(verifier, VT_MAPID) &&
           VerifyField<stXY>(verifier, VT_STARTLOC) &&
           VerifyField<int16_t>(verifier, VT_NULLBIN) &&
           VerifyField<int8_t>(verifier, VT_BINCODEFORMAT) &&
           verifier.EndTable();
  }
};

struct MAPBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_maxRow(int16_t maxRow) {
    fbb_.AddElement<int16_t>(MAP::VT_MAXROW, maxRow, 0);
  }
  void add_maxCol(int16_t maxCol) {
    fbb_.AddElement<int16_t>(MAP::VT_MAXCOL, maxCol, 0);
  }
  void add_map(flatbuffers::Offset<flatbuffers::Vector<int16_t>> map) {
    fbb_.AddOffset(MAP::VT_MAP, map);
  }
  void add_targetDie(flatbuffers::Offset<flatbuffers::Vector<const stXY *>> targetDie) {
    fbb_.AddOffset(MAP::VT_TARGETDIE, targetDie);
  }
  void add_refDie(flatbuffers::Offset<flatbuffers::Vector<const stXY *>> refDie) {
    fbb_.AddOffset(MAP::VT_REFDIE, refDie);
  }
  void add_refChipDir(int16_t refChipDir) {
    fbb_.AddElement<int16_t>(MAP::VT_REFCHIPDIR, refChipDir, 0);
  }
  void add_refNotch(int16_t refNotch) {
    fbb_.AddElement<int16_t>(MAP::VT_REFNOTCH, refNotch, 0);
  }
  void add_degRotated(int16_t degRotated) {
    fbb_.AddElement<int16_t>(MAP::VT_DEGROTATED, degRotated, 0);
  }
  void add_dieSizeX(float dieSizeX) {
    fbb_.AddElement<float>(MAP::VT_DIESIZEX, dieSizeX, 0.0f);
  }
  void add_dieSizeY(float dieSizeY) {
    fbb_.AddElement<float>(MAP::VT_DIESIZEY, dieSizeY, 0.0f);
  }
  void add_dieGapX(float dieGapX) {
    fbb_.AddElement<float>(MAP::VT_DIEGAPX, dieGapX, 0.0f);
  }
  void add_dieGapY(float dieGapY) {
    fbb_.AddElement<float>(MAP::VT_DIEGAPY, dieGapY, 0.0f);
  }
  void add_edgeClearance(float edgeClearance) {
    fbb_.AddElement<float>(MAP::VT_EDGECLEARANCE, edgeClearance, 5.0f);
  }
  void add_diameter(float diameter) {
    fbb_.AddElement<float>(MAP::VT_DIAMETER, diameter, 200.0f);
  }
  void add_waferNum(flatbuffers::Offset<flatbuffers::String> waferNum) {
    fbb_.AddOffset(MAP::VT_WAFERNUM, waferNum);
  }
  void add_waferFab(flatbuffers::Offset<flatbuffers::String> waferFab) {
    fbb_.AddOffset(MAP::VT_WAFERFAB, waferFab);
  }
  void add_fabCode(flatbuffers::Offset<flatbuffers::String> fabCode) {
    fbb_.AddOffset(MAP::VT_FABCODE, fabCode);
  }
  void add_intCode(flatbuffers::Offset<flatbuffers::String> intCode) {
    fbb_.AddOffset(MAP::VT_INTCODE, intCode);
  }
  void add_lotNum(flatbuffers::Offset<flatbuffers::String> lotNum) {
    fbb_.AddOffset(MAP::VT_LOTNUM, lotNum);
  }
  void add_device(flatbuffers::Offset<flatbuffers::String> device) {
    fbb_.AddOffset(MAP::VT_DEVICE, device);
  }
  void add_designId(flatbuffers::Offset<flatbuffers::String> designId) {
    fbb_.AddOffset(MAP::VT_DESIGNID, designId);
  }
  void add_layout(flatbuffers::Offset<flatbuffers::String> layout) {
    fbb_.AddOffset(MAP::VT_LAYOUT, layout);
  }
  void add_scribId(flatbuffers::Offset<flatbuffers::String> scribId) {
    fbb_.AddOffset(MAP::VT_SCRIBID, scribId);
  }
  void add_scribLot(flatbuffers::Offset<flatbuffers::String> scribLot) {
    fbb_.AddOffset(MAP::VT_SCRIBLOT, scribLot);
  }
  void add_mapId(int16_t mapId) {
    fbb_.AddElement<int16_t>(MAP::VT_MAPID, mapId, 0);
  }
  void add_startLoc(const stXY *startLoc) {
    fbb_.AddStruct(MAP::VT_STARTLOC, startLoc);
  }
  void add_nullBin(int16_t nullBin) {
    fbb_.AddElement<int16_t>(MAP::VT_NULLBIN, nullBin, 0);
  }
  void add_bincodeFormat(format bincodeFormat) {
    fbb_.AddElement<int8_t>(MAP::VT_BINCODEFORMAT, static_cast<int8_t>(bincodeFormat), 1);
  }
  explicit MAPBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MAPBuilder &operator=(const MAPBuilder &);
  flatbuffers::Offset<MAP> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MAP>(end);
    return o;
  }
};

inline flatbuffers::Offset<MAP> CreateMAP(
    flatbuffers::FlatBufferBuilder &_fbb,
    int16_t maxRow = 0,
    int16_t maxCol = 0,
    flatbuffers::Offset<flatbuffers::Vector<int16_t>> map = 0,
    flatbuffers::Offset<flatbuffers::Vector<const stXY *>> targetDie = 0,
    flatbuffers::Offset<flatbuffers::Vector<const stXY *>> refDie = 0,
    int16_t refChipDir = 0,
    int16_t refNotch = 0,
    int16_t degRotated = 0,
    float dieSizeX = 0.0f,
    float dieSizeY = 0.0f,
    float dieGapX = 0.0f,
    float dieGapY = 0.0f,
    float edgeClearance = 5.0f,
    float diameter = 200.0f,
    flatbuffers::Offset<flatbuffers::String> waferNum = 0,
    flatbuffers::Offset<flatbuffers::String> waferFab = 0,
    flatbuffers::Offset<flatbuffers::String> fabCode = 0,
    flatbuffers::Offset<flatbuffers::String> intCode = 0,
    flatbuffers::Offset<flatbuffers::String> lotNum = 0,
    flatbuffers::Offset<flatbuffers::String> device = 0,
    flatbuffers::Offset<flatbuffers::String> designId = 0,
    flatbuffers::Offset<flatbuffers::String> layout = 0,
    flatbuffers::Offset<flatbuffers::String> scribId = 0,
    flatbuffers::Offset<flatbuffers::String> scribLot = 0,
    int16_t mapId = 0,
    const stXY *startLoc = 0,
    int16_t nullBin = 0,
    format bincodeFormat = format_Ascii) {
  MAPBuilder builder_(_fbb);
  builder_.add_startLoc(startLoc);
  builder_.add_scribLot(scribLot);
  builder_.add_scribId(scribId);
  builder_.add_layout(layout);
  builder_.add_designId(designId);
  builder_.add_device(device);
  builder_.add_lotNum(lotNum);
  builder_.add_intCode(intCode);
  builder_.add_fabCode(fabCode);
  builder_.add_waferFab(waferFab);
  builder_.add_waferNum(waferNum);
  builder_.add_diameter(diameter);
  builder_.add_edgeClearance(edgeClearance);
  builder_.add_dieGapY(dieGapY);
  builder_.add_dieGapX(dieGapX);
  builder_.add_dieSizeY(dieSizeY);
  builder_.add_dieSizeX(dieSizeX);
  builder_.add_refDie(refDie);
  builder_.add_targetDie(targetDie);
  builder_.add_map(map);
  builder_.add_nullBin(nullBin);
  builder_.add_mapId(mapId);
  builder_.add_degRotated(degRotated);
  builder_.add_refNotch(refNotch);
  builder_.add_refChipDir(refChipDir);
  builder_.add_maxCol(maxCol);
  builder_.add_maxRow(maxRow);
  builder_.add_bincodeFormat(bincodeFormat);
  return builder_.Finish();
}

inline flatbuffers::Offset<MAP> CreateMAPDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int16_t maxRow = 0,
    int16_t maxCol = 0,
    const std::vector<int16_t> *map = nullptr,
    const std::vector<stXY> *targetDie = nullptr,
    const std::vector<stXY> *refDie = nullptr,
    int16_t refChipDir = 0,
    int16_t refNotch = 0,
    int16_t degRotated = 0,
    float dieSizeX = 0.0f,
    float dieSizeY = 0.0f,
    float dieGapX = 0.0f,
    float dieGapY = 0.0f,
    float edgeClearance = 5.0f,
    float diameter = 200.0f,
    const char *waferNum = nullptr,
    const char *waferFab = nullptr,
    const char *fabCode = nullptr,
    const char *intCode = nullptr,
    const char *lotNum = nullptr,
    const char *device = nullptr,
    const char *designId = nullptr,
    const char *layout = nullptr,
    const char *scribId = nullptr,
    const char *scribLot = nullptr,
    int16_t mapId = 0,
    const stXY *startLoc = 0,
    int16_t nullBin = 0,
    format bincodeFormat = format_Ascii) {
  return MitMAP::CreateMAP(
      _fbb,
      maxRow,
      maxCol,
      map ? _fbb.CreateVector<int16_t>(*map) : 0,
      targetDie ? _fbb.CreateVectorOfStructs<stXY>(*targetDie) : 0,
      refDie ? _fbb.CreateVectorOfStructs<stXY>(*refDie) : 0,
      refChipDir,
      refNotch,
      degRotated,
      dieSizeX,
      dieSizeY,
      dieGapX,
      dieGapY,
      edgeClearance,
      diameter,
      waferNum ? _fbb.CreateString(waferNum) : 0,
      waferFab ? _fbb.CreateString(waferFab) : 0,
      fabCode ? _fbb.CreateString(fabCode) : 0,
      intCode ? _fbb.CreateString(intCode) : 0,
      lotNum ? _fbb.CreateString(lotNum) : 0,
      device ? _fbb.CreateString(device) : 0,
      designId ? _fbb.CreateString(designId) : 0,
      layout ? _fbb.CreateString(layout) : 0,
      scribId ? _fbb.CreateString(scribId) : 0,
      scribLot ? _fbb.CreateString(scribLot) : 0,
      mapId,
      startLoc,
      nullBin,
      bincodeFormat);
}

inline const MitMAP::MAP *GetMAP(const void *buf) {
  return flatbuffers::GetRoot<MitMAP::MAP>(buf);
}

inline const MitMAP::MAP *GetSizePrefixedMAP(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<MitMAP::MAP>(buf);
}

inline bool VerifyMAPBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<MitMAP::MAP>(nullptr);
}

inline bool VerifySizePrefixedMAPBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<MitMAP::MAP>(nullptr);
}

inline void FinishMAPBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<MitMAP::MAP> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMAPBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<MitMAP::MAP> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace MitMAP

#endif  // FLATBUFFERS_GENERATED_MITMAP_MITMAP_H_
