// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RUNMODE_NSRUNMODE_H_
#define FLATBUFFERS_GENERATED_RUNMODE_NSRUNMODE_H_

#include "flatbuffers/flatbuffers.h"

namespace nsRunMode {

enum eLngRunMode {
  eLngRunMode_IN_RUN_MODE = 0,
  eLngRunMode_IN_MAINTENANCE_MODE = 1,
  eLngRunMode_MSGID = 2,
  eLngRunMode_PADDING01 = 3,
  eLngRunMode_MAX_LNG_RUNMODE_ITEM = 4,
  eLngRunMode_MIN = eLngRunMode_IN_RUN_MODE,
  eLngRunMode_MAX = eLngRunMode_MAX_LNG_RUNMODE_ITEM
};

inline const eLngRunMode (&EnumValueseLngRunMode())[5] {
  static const eLngRunMode values[] = {
    eLngRunMode_IN_RUN_MODE,
    eLngRunMode_IN_MAINTENANCE_MODE,
    eLngRunMode_MSGID,
    eLngRunMode_PADDING01,
    eLngRunMode_MAX_LNG_RUNMODE_ITEM
  };
  return values;
}

inline const char * const *EnumNameseLngRunMode() {
  static const char * const names[] = {
    "IN_RUN_MODE",
    "IN_MAINTENANCE_MODE",
    "MSGID",
    "PADDING01",
    "MAX_LNG_RUNMODE_ITEM",
    nullptr
  };
  return names;
}

inline const char *EnumNameeLngRunMode(eLngRunMode e) {
  const size_t index = static_cast<int>(e);
  return EnumNameseLngRunMode()[index];
}

}  // namespace nsRunMode

#endif  // FLATBUFFERS_GENERATED_RUNMODE_NSRUNMODE_H_
